### ISSUE TITLE
Missing executeable?

### ISSUE THREAD

**Issue by clintonholder** [keijiro/FFmpegRecorder#2]
Where do you have to install FFmpeg to use this script? I have FFmpeg build installed and PATH variables set up. Thanks
Console Error:
Failed to initialize an FFmpeg session due to missing executable file. Please check FFmpeg installation.
UnityEngine.Debug:LogError(Object)
FFmpegOut.Recorder.FfmpegRecorder:BeginRecording(RecordingSession) (at Assets/FFmpegRecorder-master/Packages/jp.keijiro.recorder.ffmpeg/Editor/FfmpegRecorder.cs:22)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by keijiro** [comment]
You have to use Package Manager to resolve dependencies correctly. Please check the "How To Install" section in README.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.
