### ISSUE TITLE
Unity Recorder 2.2.0

### ISSUE THREAD

**Issue by RubenFro** [keijiro/FFmpegRecorder#3]
With Unity Recorder 2.2.0 the OutputWidth and OutputHeight are exposed, so there's no need to use GetOutputWidth() in FFMpegRecorderUtil.cs.

FfmpegRecorder.cs, line 35 can be changed from
`+ " -video_size " + input.GetOutputWidth() + "x" + input.GetOutputHeight()`
to
`+ " -video_size " + input.OutputWidth + "x" + input.OutputHeight`

**Comment by keijiro** [comment]
Thanks for pointing it out. I fixed it in the latest commit.
