### ISSUE TITLE
Alpha channel

### ISSUE THREAD

**Issue by rsodre** [keijiro/FFmpegRecorder#4]
Hey!

Can FFmpegRecorder export the alpha when using the HAP Alpha codec?
My camera clear flags is Solid Color with black and alpha 0.
Since for image sequence, PNG alpha is only enabled for Targeted Camera, I tried that too, no Alpha option appears.

Thanks,
Roger

**Comment by keijiro** [comment]
For HDRP, see: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@7.2/manual/Alpha-Output.html

I'm closing this issue. Reopen it if you're using other render pipelines.

**Comment by rsodre** [comment]
I'm using the standard renderer, an empty 2D template.

**Comment by keijiro** [comment]
Then it should work without any special configuration.

**Comment by rsodre** [comment]
On the defaullt Movie exporter, when ProRes 4444 is selected, it displays an "Enable Alpha" (or someihng similar)
Using FFmpegRecorder, there's nothing like it, for HAP Alpha or ProRes 4444.

**Comment by keijiro** [comment]
FFmpegRecorder exports alpha when a specified codec supports alpha. So, if you select HAP Alpha or ProRes4444, it exports alpha without any special setting.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.
