### ISSUE TITLE
Output resolution does not overwrite Game View resolution

### ISSUE THREAD

**Issue by struzjos** [keijiro/FFmpegRecorder#7]
Reproduction:
1. Add Ffmpeg recorder in recorder window
2. Set Output Resolution to for example 1080p
3. Open Game window
4. Set resolution in Game window to for example 60:40
5. Hit start recording
6. The output video will be 1080p but stretched from 60:40 (blurry)

**Comment by keijiro** [comment]
Does it reproduce with the built-in movie exporter of Unity Recorder?

**Comment by struzjos** [comment]
Built-in movie exporter is working fine, problem is just with Ffmpeg. It does not resize to Output resolution. In preview everything seems to be OK, but the output video file is blurry.

**Comment by struzjos** [comment]
I am using Unity 2020.1.11f, Unity Recorder 2.4.0-preview.1, FFmpeg Recorder 1.0.2 and FFmpegOut 1.0.5

**Comment by keijiro** [comment]
I'm using 2020.1.15f1, but it doesn't reproduce on my side.

Could you check if it's reproducible with the test project (the project in this repository)?

**Comment by keijiro** [comment]
I heard that this is a regression issue on Unity Recorder 2.4.0. Please wait for a fix on the Recorder side.

**Comment by keijiro** [comment]
It will be fixed in Recorder 2.5.1.

**Comment by keijiro** [comment]
FYI: Fixed in Recorder 2.5.2 https://forum.unity.com/threads/unity-recorder-update.509458/page-14#post-6647173
